---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: mpaivabarbosa/molecule-systemd-ubuntu:20.04
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
